name: Some Job Using DynamoDB Local

on: workflow_dispatch

jobs:
  some_job_using_dynamodb_local:
    runs_on: ubuntu-latest

    # services で localhost:8000 で dynamodb-local を起動する
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          8000:8000

    steps:

      - name: Setup DynamoDB Local
        env:
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
          AWS_DEFAULT_REGION: ap-northeast-1

        run: |
          aws dynamodb create-table --endpoint-url http://localhost:8000 \
            --table-name your_table_name \
            --attribute-definitions AttributeName=hoge,AttributeType=S \
            --key-schema AttributeName=hoge,KeyType=HASH \
            --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1

      - name: Check DynamoDB Table
        env:
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
          AWS_DEFAULT_REGION: ap-northeast-1
        run: aws dynamodb describe-table --endpoint-url http://localhost:8000 --table-name your_table_name

